language: php

php:
  - 7.4

setup_env: &setup_env
  before_script:
    - composer install --no-interaction
    - cp .env.example .env
    - php artisan key:generate

jobs:
  include:
    - stage: "Lint Code"
      <<: *setup_env
      script:
        - make format_check
    - stage: "Tests"
      name: "Unit Test PHP"
      services:
        - mysql
      <<: *setup_env
      script: 
        - php artisan test