language: php

php:
  - 7.4

setup_env: &setup_env
  before_script:
    - composer install --no-interaction

jobs:
  include:
    - stage: "Lint Code"
      <<: *setup_env
      script:
        - make format_check